server:
  port: 1963

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  format_sql: true
  envers:
    store_data_at_delete: true
  jdbc:
    lob:
      non_contextual_creation: true

spring:
  datasource:
#    url: jdbc:postgresql://localhost:64321/mutants_xmen
    url: jdbc:postgresql://ec2-52-44-31-100.compute-1.amazonaws.com:5432/d66lkjl7t7vbep
#    username: xmen
    username: vciigxqwisykqs
#    password: mutants1234@xmen
    password: e90a1b1e0ef4fa926ffe3bef937a4f9e451d203e00fc309d94ad3284e9f95941
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  liquibase:
    default-schema: brotherhood_of_mutants
    change-log: classpath:db_version_control/changelog-master.xml
